### ISSUE TITLE
'platform' component: Insert similarity rating between platforms based on relevance to selected subject

### ISSUE THREAD

**Issue by evaristoc** [evaristoc/fCC_R3_DataAnalysis#8]
## Problem Description
(...)

## User Story
- [ ] The top10 "Similar Platforms" are those in the same category that are similar AND have the highest ranking for the selected subject: Scat_mat x Rankingsubj_diag
- [ ] The top10 "Mentioned by" are those of any category mentioned by other users that are similar AND have the highest ranking for the selected subject: Sment_mat x Rankingsubj_diag

## Technical Specs
- [ ] (...)

## Possible Solutions
* ~Implement on the fly using Lambda functions~ No, at least not now. Introduce several operational and technological issues that might not be practical
* ~Look for a cloud service~ This could be a good option too: to be explored...
* Simple cosine similarity rating, likely kNN; sklearn implementation: all before data is loaded. Some reasons why the solutions above were discharged are: 
  * Firebase not good for querying
  * They introduce additional, complex async behaviour and waiting
  * This project is currently based on client browser so it is slow and no much memory
  * The section for which this is implemented is not considered as critical as other areas right now

## Milestones
- [x] Prepare a simple demo: top10 "Similar Platforms" the first 10 of same category that are similar; top10 "Mentioned by" just the first 10 more similar no matter the category
---

### Warnings and Notes:
* relates to https://github.com/evaristoc/fCC_R3/issues/11, https://github.com/evaristoc/fCC_R3/issues/16 and https://github.com/evaristoc/fCC_R3_DataAnalysis/milestone/1

### References
* https://stackoverflow.com/questions/17627219/whats-the-fastest-way-in-python-to-calculate-cosine-similarity-given-sparse-mat
