### ISSUE TITLE
Data Revision

### ISSUE THREAD

**Issue by evaristoc** [evaristoc/fCC_R3_DataAnalysis#9]
## Problem Description
This is a control of several issues already opened and the milestone number 1.

## User Story
- [x] (...)

## Technical Specs
- [x] add the wikipedia info to the current db
- [x] correct subject word lists
- [x] work on the ranking per subject
- [x] ~include a list of keywords based on subject relevance~ not a good idea
- [x] similar platforms: implement kNN/cosine similarity for comparisons between platforms based on ranking per subject; 10 per subject
- [x] other people's selection: identify other mentions of platforms and find similarities as above (?); 10 per subject
- [x] ~update last date~ not at this iteration

## Possible Solutions
* (...)

## Milestones
- [x] https://github.com/evaristoc/fCC_R3_DataAnalysis/milestone/1

---

### Warnings and Notes:
* Refers to issues #6, #7, #8

### References:
* (...)

**Comment by evaristoc** [comment]
The last milestone was reached
